packages:
  - apps/*
  - packages/*

allowBuilds:
  "@scarf/scarf": false
  bcrypt: set this to true or false
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
